package gr.knowledge.internship.demo.repository;

import gr.knowledge.internship.demo.domain.OrderDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;
import java.util.Optional;

@Repository
public interface OrderDetailsRepository extends JpaRepository<OrderDetails, Long>{

    /*5.Write a query to retrieve the total revenue generated by the store in the last month.*/
    //List<OrderDetails> getAllByPrice(String productCategory, Sort sort);


    /* a */

    @Query("SELECT od FROM OrderDetails od WHERE (od.productId = :id)")
    Optional<OrderDetails> getOrderDetailsById(@Param("id") Long id);

    @Query("SELECT od FROM OrderDetails od WHERE (od.quantity = :quantity)")
    Optional<OrderDetails> getByQuantity(@Param("quantity") Long quantity);

    /* 6 */
    @Query("SELECT od FROM OrderDetails od INNER JOIN Orders o ON od.orderId = o.orderId WHERE o.orderDate BETWEEN :startDate AND :endDate")
    List<OrderDetails> getProductsOfTheWeek2(@Param("startDate") Date startDate, @Param("endDate") Date endDate);

}
